steps:
  - id: build-cromwell
    name: us.gcr.io/broad-dsde-cromwell-dev/cromwell-cloudbuild-base
    entrypoint: bash
    args:
      - src/ci/bin/test.sh
    env:
    - 'BUILD_TYPE=sbt'
    - 'CLOUD_BUILD=true'
    - 'crmdbg=y'
    timeout: 3600s
options:
  machineType: 'N1_HIGHCPU_8'
  diskSizeGb: '100'
timeout: 3600s
