steps:
  - id: build-cromwell
    name: hseeberger/scala-sbt:8u265_1.4.3_2.13.4
    entrypoint: src/ci/bin/test.sh
    env:
    - 'BUILD_TYPE=sbt'
    timeout: 3600s
options:
  machineType: 'N1_HIGHCPU_32'
  diskSizeGb: '500'
timeout: 3600s
