steps:
  - id: build-cromwell
    # Container is https://hub.docker.com/r/hseeberger/scala-sbt plus Docker, vault, git-secrets
    name: us.gcr.io/broad-dsde-cromwell-dev/cromwell-cloudbuild-base@sha256:973e10cec360d1b36a305ef61e6bc3dcaae8a7b76f81c131e982838409cd5cf1
    entrypoint: bash
    args:
      - src/ci/bin/test.sh
    env:
    - 'BUILD_TYPE=sbt'
    - 'CLOUD_BUILD=true'
    - 'crmdbg=y'
    timeout: 3600s
options:
  machineType: 'N1_HIGHCPU_32'
  diskSizeGb: '100'
timeout: 3600s
