steps:
  - id: build-cromwell
    name: us.gcr.io/broad-dsde-cromwell-dev/cromwell-cloudbuild-base
    entrypoint: bash
    args:
      - src/ci/bin/testSbt.sh
    env:
    - 'BUILD_TYPE=sbt'
    - 'CROMWELL_BUILD_IS_CI=true'
    timeout: 3600s
options:
  machineType: 'N1_HIGHCPU_32'
  diskSizeGb: '500'
timeout: 3600s
