steps:
  # The `cromwell-cloudbuild-base` image runs as a non-root user so that `CromwellCommandLineSpec` can pass
  # https://github.com/GoogleCloudPlatform/cloud-builders/issues/641#issuecomment-604599102
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      [
        '-c',
        'chmod -R 777 /workspace',
      ]
  - id: build-cromwell
    name: us.gcr.io/broad-dsde-cromwell-dev/cromwell-cloudbuild-base@sha256:9d4dfb4347c66c402b91707aa501495b52dd9c72644d39b62395191b4ad56b97
    entrypoint: bash
    args:
      - src/ci/bin/test.sh
    env:
    - 'BUILD_TYPE=sbt'
    - 'CLOUD_BUILD=true'
    - 'crmdbg=y'
    timeout: 3600s
options:
  machineType: 'N1_HIGHCPU_32'
  diskSizeGb: '100'
timeout: 3600s
