steps:
  - id: build-cromwell
    # Container is https://hub.docker.com/r/hseeberger/scala-sbt plus Docker, vault, git-secrets
    name: us.gcr.io/broad-dsde-cromwell-dev/cromwell-cloudbuild-base@sha256:cc4d53816a3f88d04a33350553779b2a46bbd29d973858da0f530e443b92e13f
    entrypoint: bash
    args:
      - src/ci/bin/test.sh
    env:
    - 'BUILD_TYPE=sbt'
    - 'CLOUD_BUILD=true'
    timeout: 3600s
options:
  machineType: 'N1_HIGHCPU_32'
  diskSizeGb: '100'
timeout: 3600s
