version: 2.1

#orbs:
#  openjdk-install: cloudesire/openjdk-install@1.2.3

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - run: java -version
      - run: docker version
      - run: docker-compose version
      - run: ls -la
      - run: src/ci/bin/test.sh
    environment:
      BUILD_TYPE: sbt
