version: 2.1

#orbs:
#  openjdk-install: cloudesire/openjdk-install@1.2.3

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - run: java -version
      - run: docker version
      - run: docker-compose version
      - run: git clone --depth 1 "$CIRCLE_REPOSITORY_URL" --branch "$CIRCLE_BRANCH" . # clone to working dir not `cromwell/`
      - run: ls -la
      - run:
          name: 'Single workflow runner'
          command: src/ci/bin/testSingleWorkflowRunner.sh
          no_output_timeout: 1h
    environment:
      BUILD_TYPE: sbt
