name: dsp-appsec-trivy
on: [pull_request]

jobs:
  appsec-trivy:
    # Parse Dockerfile and build, scan image if a "blessed" base image is not used
    name: DSP AppSec Trivy check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
        - cromiam
        - cromwell-drs-localizer
        - perf
        - server
        - statsDProxy
        - womtool

    steps:
      - uses: actions/checkout@v2

      # set up SBT cache
      - uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2
            ~/.m2
            ~/.sbt
          key: sbt-${{ matrix.project }}-${{ hashFiles('**/build.sbt') }}

      # fetch SBT package
      - uses: olafurpg/setup-scala@v10

      # build the image
      - name: Build
        id: build
        run: |
          sbt -no-colors ${{ matrix.project }}/docker | tee build.log
          image=$(grep 'Tagging image' build.log | awk '{print $NF}')
          echo "::set-output name=image::${image}"

      # # scan the image
      # - uses: broadinstitute/dsp-appsec-trivy-action@v1
      #   with:
      #     image: ${{ steps.build.outputs.image }}
